# Firefly III API Configuration
server:
  url: "https://funds.appservice.space/api"

api:
  token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjJlMDY0NDY0NWQ1NzY2YjRlNmU1OWZmMDZiZThkMDU0NWQ2YzM2NDU0Y2ZkYzQxMGRiNjIyMjgyZGY2NWNmNWU2NDJlYjJjZDFiOGZhNzMiLCJpYXQiOjE3NTM5NjY2MTAuODY4NTg0LCJuYmYiOjE3NTM5NjY2MTAuODY4NTg1LCJleHAiOjE3ODU1MDI2MTAuNzMzMjQ2LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.cik5zOFWgKrUuJIQeBlYPbHRMH9vpxS6owKa92MwNJHS2HSQhPzStpatgWF2AXQ-XQYXINP40ov7r9U8HV6WC-wTRjmvw__mKAweJpSgmHa7xQH6pkn8NYoloz5vXwr36jwtvMWtiM5WJgEYubgLELvKDX8KGt2QvN2aW6QEKegR75RK5Pd0DAd3WbssS691IV5HVSz4iHoHvOnjqB_5IInnvdAF2CuGdkFU7le1G_buryCHPc_A1E4TyG6I3A93jSZ_nkU7N0XhxdxZOcR4CM4SojMLut-kinW0MHhUlsEgaZzb3GO4cPiJu1Teh3F5z85HKnu3j85TNQul660VpFp5oIeFouMkjgEGXS_CGyRmyFO1bzHowUK6FIPQ1IL6KnmiQ2s38uzocEqXwyRVA4Zqqym0oYjU2TFsE3HPU-vTvIeNBCtTzGeA6U9TmuLfRnSjkKJWeWxuxZiqSyx9ZdtBo7hlwIhxY9TUTO7izKO9_vOUeABLhM-oWcGPwd5G6A6g6IKdlDVl53d7GD3kVly-5y-nysozTZqpXo_CmtP58zT9aHlei9KJGjaKBrhZws1idorr3M3r2xu-VnPe0uFchiRhkFDHuV15zSr32YJVnD0TsFOJ1JsqhilQpyinr2xHEIQJhZIIrPFD2ZRCnEZ8o9YdRbos8UU7-nppH8I"

client:
  timeout: 30 # timeout in seconds

# Example limits for API calls
limits:
  accounts: 10
  transactions: 5
  categories: 10
  budgets: 10

# MCP server configuration
mcp:
  name: "firefly-iii-mcp"
  version: "1.0.0"
  instructions: "MCP server for Firefly III personal finance management"